### ISSUE TITLE
Publish TYPO3 Extension for this package on Packagist

### ISSUE THREAD

**Issue by pixelbrackets** [xqueue/maileon-php-api-client#11]
Hey - Thanks for the [public package](https://packagist.org/packages/xqueue/maileon-api-client) of this API client. You also provide a TYPO3 extension which utilities this package: 
https://extensions.typo3.org/extension/typo3_maileon_integration

Could you please publish this extension package via Packagist as well?

Right now we have to load this extension through a [deprecated workaround process](https://get.typo3.org/misc/composer/repository) provided by the TYPO3 extension repository.

This would easen the integration of your package. 👍

**Comment by mbeckerle-xqueue** [comment]
Hi,

we are discussing possibilities and I will come back to you as soon as we clarified what we can provide.

Kind regards,
Marcus

**Comment by mbeckerle-xqueue** [comment]
I just noticed that we forgot to notify you here.

In the meanwhile, the package has been released: https://packagist.org/packages/xqueue/typo3-plugin

Kind regards,
Marcus
