### ISSUE TITLE
Wrong type of permission parameter in Contact constructor

### ISSUE THREAD

**Issue by leninzprahy** [xqueue/maileon-php-api-client#3]
The `\Maileon\Contacts\Contact` class in the constructor indicates the permission parameter as a string, but it should be `\Maileon\Contacts\Permission` instead

**Comment by mbeckerle-xqueue** [comment]
Hi,

I checked it and it is in deed a mistake in the description. I will fix it, thank you for the hint.

Kind regards,
Marcus
