### ISSUE TITLE
Salutation handling

### ISSUE THREAD

**Issue by Myrmod** [xqueue/maileon-php-api-client#9]
Hello,

I am currently implementing this extension and I have some difficulties. The problem is, that in the example code I have gotten from the Maileon Backend PHP-Code generator I have a Salutation field that looks like this:

```php
<input type="text" placeholder="Anrede" name="standard_0" id="standard_0" maxlength="255" value="<?= $standard_0 ?>" class="form-control">
```

Usually people use a `HTMLSelectElement` for this, but whatever. The issue is, that the MaileonAPI seems to expect some key, and not a simple string for the salutation used in the newsletter.

- So what are the existing keys? 
- How do I define new keys?
- How are multiple languages handled?

Best regards

**Comment by mbeckerle-xqueue** [comment]
I will close the issue, if you have further questions, just post an update and reopen the issue.

Kind regards,
Marcus
